"""Generate the dependency-free wire field layer consumed by the supported client."""

from __future__ import annotations

import argparse
import ast
import keyword
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MODELS = (
    "HistoryRow",
    "HistoryPage",
    "DomainProfile",
    "IdentificationScoredData",
    "IdentificationScoredEvent",
    "WebhookPingEvent",
    "IpInfo",
    "LocalIpInfo",
    "TrafficSource",
    "Signal",
    "DetectionFlags",
    "ScoreDetail",
)


def render(document: dict) -> str:
    def resolve(schema: dict) -> dict:
        if "$ref" in schema:
            ref = schema["$ref"]
            if not ref.startswith("#/"):
                raise ValueError("Only bundled local references are supported")
            value = document
            for part in ref[2:].split("/"):
                value = value[part]
            return resolve(value)
        return schema

    def wire_type(schema: dict) -> str:
        schema = resolve(schema)
        kind = schema.get("type")
        if isinstance(kind, list):
            return "Union[" + ", ".join(wire_type({**schema, "type": t}) for t in kind) + "]"
        if kind == "object":
            return "Mapping[str, object]"
        if kind == "array":
            return "list[" + wire_type(schema["items"]) + "]"
        primitives = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "null": "None",
        }
        if kind not in primitives:
            raise ValueError(f"Unsupported wire schema: {schema}")
        return primitives[kind]

    lines = [
        '"""Generated by scripts/generate_wire.py; do not edit manually.',
        "",
        "Types describe the wire contract, not runtime validation. Field.read preserves",
        "missing, malformed and unknown data for the tolerant normalization boundary.",
        '"""',
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping",
        "from typing import Generic, Literal, Optional, TypedDict, TypeVar, Union, cast",
        "",
        'T = TypeVar("T", covariant=True)',
        "",
        "class Field(Generic[T]):",
        "    def __init__(self, name: str) -> None:",
        "        self.name = name",
        "",
        "    def read(self, value: Mapping[str, object]) -> Optional[T]:",
        "        return cast(Optional[T], value.get(self.name))",
        "",
    ]
    operations = {}
    routes = {}
    methods = {}
    for surface in (document["paths"], document.get("webhooks", {})):
        for route, path in surface.items():
            for method, operation in path.items():
                if isinstance(operation, dict) and "operationId" in operation:
                    operation_id = operation["operationId"]
                    operations[operation_id] = operation
                    routes[operation_id] = route
                    methods[operation_id] = method
                    # Operation parameters override inherited parameters with the same key.
                    merged = {}
                    for parameter in [
                        *path.get("parameters", []),
                        *operation.get("parameters", []),
                    ]:
                        parameter = resolve(parameter)
                        merged[(parameter["in"], parameter["name"])] = parameter
                    operations[operation_id] = {**operation, "parameters": list(merged.values())}
    supported = {
        "searchHistory": {
            ("path", "search_type"),
            ("path", "value"),
            ("query", "limit"),
            ("query", "offset"),
        },
        "getDomainProfile": {("header", "X-Shield-Domain")},
    }
    for operation_id, allowed in supported.items():
        if methods[operation_id] != "get":
            raise ValueError(f"Unsupported HTTP method on {operation_id}: {methods[operation_id]}")
        for parameter in operations[operation_id]["parameters"]:
            key = (parameter["in"], parameter["name"])
            if parameter.get("required", False) and key not in allowed:
                raise ValueError(f"Unsupported required parameter on {operation_id}: {key}")
    lookup_parameter = next(
        parameter
        for parameter in operations["searchHistory"]["parameters"]
        if (parameter["in"], parameter["name"]) == ("path", "search_type")
    )
    # The schema may expose a new lookup before its validation rules exist in this client.
    validation = ast.parse((ROOT / "src/shieldlabs/_validation.py").read_text())
    lookup_types = next(
        ast.literal_eval(statement.value)
        for statement in validation.body
        if isinstance(statement, ast.AnnAssign)
        and isinstance(statement.target, ast.Name)
        and statement.target.id == "LOOKUP_TYPES"
    )
    if set(resolve(lookup_parameter["schema"])["enum"]) != set(lookup_types):
        raise ValueError("Unsupported lookup types: update client validation before generation")
    history_route = routes["searchHistory"]
    if set(re.findall(r"\{([^{}]+)\}", history_route)) != {"search_type", "value"}:
        raise ValueError("Unsupported History path placeholders")
    lines.extend(
        [
            f"PROFILE_PATH = {routes['getDomainProfile']!r}",
            f"HISTORY_PATH = {history_route!r}",
            "",
        ]
    )
    schemas = {
        name: resolve(document["components"]["schemas"][name])
        for name in MODELS
        if name != "LocalIpInfo"
    }
    for name, operation_id in (
        ("HistoryPage", "searchHistory"),
        ("DomainProfile", "getDomainProfile"),
    ):
        response = resolve(operations[operation_id]["responses"]["200"])
        schemas[name] = resolve(response["content"]["application/json"]["schema"])
    for name, operation_id in (
        ("IdentificationScoredEvent", "identificationScored"),
        ("WebhookPingEvent", "webhookPing"),
    ):
        body = resolve(operations[operation_id]["requestBody"])
        schemas[name] = resolve(body["content"]["application/json"]["schema"])
    for name, expected in (
        ("IdentificationScoredEvent", "identification.scored"),
        ("WebhookPingEvent", "webhook.ping"),
    ):
        discriminator = schemas[name]["properties"].get("event_type")
        if discriminator is None:
            raise ValueError(f"Unsupported webhook discriminator on {name}: missing event_type")
        discriminator = resolve(discriminator)
        if wire_type(discriminator) != "str" or discriminator.get("const") != expected:
            raise ValueError(f"Unsupported webhook discriminator on {name}")
    schemas["HistoryRow"] = resolve(schemas["HistoryPage"]["properties"]["data"]["items"])
    schemas["IdentificationScoredData"] = resolve(
        schemas["IdentificationScoredEvent"]["properties"]["data"]
    )
    data = schemas["IdentificationScoredData"]["properties"]
    for name, key in (
        ("IpInfo", "public_ip"),
        ("LocalIpInfo", "local_ip"),
        ("TrafficSource", "traffic_source"),
        ("DetectionFlags", "detection_flags"),
    ):
        schemas[name] = resolve(data[key])
    schemas["Signal"] = resolve(data["signals"]["items"])
    for name in MODELS:
        schema = schemas[name]
        lines.append(f"class {name}:")
        for key, prop in schema["properties"].items():
            if not key.isidentifier() or keyword.iskeyword(key):
                raise ValueError(f"Unsupported Python field name: {key}")
            lines.append(f"    {key}: Field[{wire_type(prop)}] = Field({key!r})")
        lines.append("")

    for operation_id, location, name in (
        ("searchHistory", "query", "HistoryQuery"),
        ("searchHistory", "path", "HistoryPath"),
        ("getDomainProfile", "header", "ProfileHeaders"),
    ):
        parameters = [resolve(p) for p in operations[operation_id]["parameters"]]
        required_fields = {}
        optional_fields = {}
        for p in parameters:
            if p["in"] != location:
                continue
            schema = resolve(p["schema"])
            annotation = wire_type(schema)
            if "enum" in schema:
                annotation = "Literal[" + ", ".join(repr(v) for v in schema["enum"]) + "]"
                if name == "HistoryPath" and p["name"] == "search_type":
                    lines.append(f"LookupType = {annotation}")
            fields = required_fields if p.get("required", False) else optional_fields
            fields[p["name"]] = annotation
        bases = []
        for suffix, fields, required in (
            ("Required", required_fields, True),
            ("Optional", optional_fields, False),
        ):
            base = f"_{name}{suffix}"
            bases.append(base)
            if all(key.isidentifier() and not keyword.iskeyword(key) for key in fields):
                lines.append(f"class {base}(TypedDict, total={required}):")
                lines.extend(f"    {key}: {annotation}" for key, annotation in fields.items())
                if not fields:
                    lines.append("    pass")
            else:
                entries = ", ".join(f"{key!r}: {annotation}" for key, annotation in fields.items())
                lines.append(f"{base} = TypedDict({base!r}, {{{entries}}}, total={required})")
            lines.append("")
        lines.extend([f"class {name}({', '.join(bases)}):", "    pass"])
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=ROOT / "resources/shieldlabs-api.yaml")
    parser.add_argument("--output", type=Path, default=ROOT / "src/shieldlabs/_generated_wire.py")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = render(yaml.safe_load(args.schema.read_text()))
    # Pin formatting to the same tool used by the repository, not host line endings.
    formatted = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--config",
            str(ROOT / "pyproject.toml"),
            "--stdin-filename",
            "src/shieldlabs/_generated_wire.py",
            "-",
        ],
        input=source,
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    formatted = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--config",
            str(ROOT / "pyproject.toml"),
            "--stdin-filename",
            "src/shieldlabs/_generated_wire.py",
            "-",
        ],
        input=formatted,
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    if args.check:
        if not args.output.exists() or args.output.read_text() != formatted:
            print("Wire types are stale; run python scripts/generate_wire.py", file=sys.stderr)
            return 1
    else:
        args.output.write_text(formatted)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
