"""Generated by scripts/generate_wire.py; do not edit manually.

Types describe the wire contract, not runtime validation. Field.read preserves
missing, malformed and unknown data for the tolerant normalization boundary.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Generic, Literal, Optional, TypedDict, TypeVar, Union, cast

T = TypeVar("T", covariant=True)


class Field(Generic[T]):
    def __init__(self, name: str) -> None:
        self.name = name

    def read(self, value: Mapping[str, object]) -> Optional[T]:
        return cast(Optional[T], value.get(self.name))


PROFILE_PATH = "/v1/profile"
HISTORY_PATH = "/api/v1/history/{search_type}/{value}"


class HistoryRow:
    request_id: Field[str] = Field("request_id")
    session_id: Field[str] = Field("session_id")
    cookie_id: Field[str] = Field("cookie_id")
    domain: Field[str] = Field("domain")
    site_domain: Field[str] = Field("site_domain")
    user_hid: Field[str] = Field("user_hid")
    device_id: Field[str] = Field("device_id")
    visitor_id: Field[str] = Field("visitor_id")
    ip: Field[str] = Field("ip")
    os: Field[str] = Field("os")
    browser: Field[str] = Field("browser")
    device_type: Field[str] = Field("device_type")
    country: Field[str] = Field("country")
    connection_type: Field[str] = Field("connection_type")
    score: Field[int] = Field("score")
    score_details: Field[str] = Field("score_details")
    created_at: Field[str] = Field("created_at")
    ver: Field[int] = Field("ver")
    web_rtc_ip: Field[str] = Field("web_rtc_ip")
    web_rtc_country: Field[str] = Field("web_rtc_country")
    web_rtc_connection_type: Field[str] = Field("web_rtc_connection_type")
    webrtc_leak_ip: Field[str] = Field("webrtc_leak_ip")
    webrtc_leak_country: Field[str] = Field("webrtc_leak_country")
    webrtc_leak_connection_type: Field[str] = Field("webrtc_leak_connection_type")
    webrtc_leak_source: Field[str] = Field("webrtc_leak_source")
    is_vpn: Field[bool] = Field("is_vpn")
    is_tor: Field[bool] = Field("is_tor")
    is_proxy: Field[bool] = Field("is_proxy")
    is_datacenter: Field[bool] = Field("is_datacenter")
    is_abuser: Field[bool] = Field("is_abuser")
    is_privacy_relay: Field[bool] = Field("is_privacy_relay")
    is_stun_not_checked: Field[bool] = Field("is_stun_not_checked")
    check_incomplete: Field[bool] = Field("check_incomplete")
    is_antidetect: Field[bool] = Field("is_antidetect")
    is_os_mismatch: Field[bool] = Field("is_os_mismatch")
    is_os_not_detected: Field[bool] = Field("is_os_not_detected")
    is_timezone_mismatch: Field[bool] = Field("is_timezone_mismatch")
    is_js_disabled: Field[bool] = Field("is_js_disabled")
    is_browser_automation: Field[bool] = Field("is_browser_automation")
    is_incognito: Field[bool] = Field("is_incognito")
    is_search_bot: Field[bool] = Field("is_search_bot")
    is_suspicious_paid_click: Field[bool] = Field("is_suspicious_paid_click")
    entry_url: Field[str] = Field("entry_url")
    utm_source: Field[str] = Field("utm_source")
    utm_medium: Field[str] = Field("utm_medium")
    utm_campaign: Field[str] = Field("utm_campaign")
    utm_content: Field[str] = Field("utm_content")
    utm_term: Field[str] = Field("utm_term")
    traffic_channel: Field[str] = Field("traffic_channel")
    traffic_channel_group: Field[str] = Field("traffic_channel_group")
    traffic_reason: Field[str] = Field("traffic_reason")
    referrer_domain: Field[str] = Field("referrer_domain")
    click_id_type: Field[str] = Field("click_id_type")


class HistoryPage:
    data: Field[list[Mapping[str, object]]] = Field("data")
    total: Field[int] = Field("total")


class DomainProfile:
    Domain: Field[str] = Field("Domain")
    Weight: Field[int] = Field("Weight")
    Callback: Field[str] = Field("Callback")
    PublicKey: Field[str] = Field("PublicKey")
    Secret: Field[str] = Field("Secret")
    CreatedAt: Field[str] = Field("CreatedAt")


class IdentificationScoredData:
    request_id: Field[str] = Field("request_id")
    visitor_id: Field[str] = Field("visitor_id")
    device_id: Field[str] = Field("device_id")
    session_id: Field[str] = Field("session_id")
    cookie_id: Field[str] = Field("cookie_id")
    user_hid: Field[Union[str, None]] = Field("user_hid")
    domain: Field[str] = Field("domain")
    public_ip: Field[Mapping[str, object]] = Field("public_ip")
    local_ip: Field[Mapping[str, object]] = Field("local_ip")
    connection_type: Field[str] = Field("connection_type")
    os: Field[str] = Field("os")
    browser: Field[str] = Field("browser")
    device_type: Field[str] = Field("device_type")
    traffic_source: Field[Mapping[str, object]] = Field("traffic_source")
    risk_score: Field[int] = Field("risk_score")
    signals: Field[list[Mapping[str, object]]] = Field("signals")
    detection_flags: Field[Mapping[str, object]] = Field("detection_flags")
    observed_at: Field[str] = Field("observed_at")


class IdentificationScoredEvent:
    event_type: Field[str] = Field("event_type")
    schema_version: Field[str] = Field("schema_version")
    created_at: Field[str] = Field("created_at")
    data: Field[Mapping[str, object]] = Field("data")


class WebhookPingEvent:
    event_type: Field[str] = Field("event_type")
    schema_version: Field[str] = Field("schema_version")
    created_at: Field[str] = Field("created_at")


class IpInfo:
    ip: Field[str] = Field("ip")
    country: Field[str] = Field("country")


class LocalIpInfo:
    ip: Field[str] = Field("ip")
    country: Field[str] = Field("country")


class TrafficSource:
    channel: Field[str] = Field("channel")
    referrer_domain: Field[str] = Field("referrer_domain")
    landing_url: Field[str] = Field("landing_url")
    click_id_type: Field[str] = Field("click_id_type")
    utm_source: Field[str] = Field("utm_source")
    utm_medium: Field[str] = Field("utm_medium")
    utm_campaign: Field[str] = Field("utm_campaign")
    utm_content: Field[str] = Field("utm_content")
    utm_term: Field[str] = Field("utm_term")


class Signal:
    name: Field[str] = Field("name")
    weight: Field[int] = Field("weight")


class DetectionFlags:
    vpn: Field[bool] = Field("vpn")
    privacy_relay: Field[bool] = Field("privacy_relay")
    browser_vpn_proxy: Field[bool] = Field("browser_vpn_proxy")
    tor: Field[bool] = Field("tor")
    proxy: Field[bool] = Field("proxy")
    datacenter_ip: Field[bool] = Field("datacenter_ip")
    abuser: Field[bool] = Field("abuser")
    os_mismatch: Field[bool] = Field("os_mismatch")
    os_not_detected: Field[bool] = Field("os_not_detected")
    timezone_mismatch: Field[bool] = Field("timezone_mismatch")
    anti_detect_browser: Field[bool] = Field("anti_detect_browser")
    browser_automation: Field[bool] = Field("browser_automation")
    ip_mismatch: Field[bool] = Field("ip_mismatch")
    incognito: Field[bool] = Field("incognito")
    search_bot: Field[bool] = Field("search_bot")
    suspicious_paid_click: Field[bool] = Field("suspicious_paid_click")
    javascript_disabled: Field[bool] = Field("javascript_disabled")
    stun_not_checked: Field[bool] = Field("stun_not_checked")
    check_incomplete: Field[bool] = Field("check_incomplete")


class ScoreDetail:
    Value: Field[int] = Field("Value")
    Description: Field[str] = Field("Description")


class _HistoryQueryRequired(TypedDict, total=True):
    pass


class _HistoryQueryOptional(TypedDict, total=False):
    limit: int
    offset: int


class HistoryQuery(_HistoryQueryRequired, _HistoryQueryOptional):
    pass


LookupType = Literal[
    "request_id", "device_id", "user_hid", "visitor_id", "ip", "session_id", "cookie_id"
]


class _HistoryPathRequired(TypedDict, total=True):
    search_type: Literal[
        "request_id", "device_id", "user_hid", "visitor_id", "ip", "session_id", "cookie_id"
    ]
    value: str


class _HistoryPathOptional(TypedDict, total=False):
    pass


class HistoryPath(_HistoryPathRequired, _HistoryPathOptional):
    pass


_ProfileHeadersRequired = TypedDict("_ProfileHeadersRequired", {"X-Shield-Domain": str}, total=True)


class _ProfileHeadersOptional(TypedDict, total=False):
    pass


class ProfileHeaders(_ProfileHeadersRequired, _ProfileHeadersOptional):
    pass
